title: Hongyu Wang's Homepage
page-top-title: Hongyu Wang
top-section-bg-text: For Future <strong>S</strong>afe, <strong>S</strong>mart, and <strong>S</strong>ustainable Infrastructure
home-subtitle: Hongyu Wang&ensp;|&ensp;王泓宇
copyright-text: '&copy; Hongyu Wang 2026-2027. All Rights Reserved.'
