title: Hongyu Wang's Homepage
page-top-title: Hongyu Wang
top-section-bg-text: Construction Management
home-subtitle: Hongyu Wang&ensp;|&ensp;王泓宇
copyright-text: '&copy; Hongyu Wang 2024-2025. All Rights Reserved.'
